<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>MultiCardSync.Data</RootNamespace>
    <AssemblyName>MultiCardSync.Data</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Sheets.v4" Version="1.*" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.*" />
    <PackageReference Include="Dapper" Version="2.*" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Core/Core.csproj" />
  </ItemGroup>

</Project>
